/**
 * Device Configurations Index
 * Exports all device type configurations
 */

import CCT_DOWNLIGHT_CONFIG from './CCT_DOWNLIGHT';
import CURTAIN_CONFIG from './CURTAIN';
import DIMMER_CONFIG from './DIMMER';
import FIVE_BUTTON_CONFIG from './FIVE_BUTTON';
import FAN_CONFIG from './FAN';
import RGB_CW_CONFIG from './RGB_CW';
import SOCKET_SWITCH_CONFIG from './SOCKET_SWITCH';
import SOCKET_RELAY_CONFIG from './SOCKET_RELAY';
import THERMOSTAT_CONFIG from './THERMOSTAT';
import DRY_CONTACT_CONFIG from './DRY_CONTACT';
import VCAL_SOCKET_CONFIG from './VCAL_SOCKET';
import T3_SWITCH_CONFIG from './T3_SWITCH';
import T3_DIMMER_CONFIG from './T3_DIMMER';
import POWER_POINT_CONFIG from './POWER_POINT';

// Device configuration mapping
export const DEVICE_CONFIGS = {
  CCT_DOWNLIGHT: CCT_DOWNLIGHT_CONFIG,
  CURTAIN: CURTAIN_CONFIG,
  DIMMER: DIMMER_CONFIG,
  FIVE_BUTTON: FIVE_BUTTON_CONFIG,
  FAN: FAN_CONFIG,
  RGB_CW: RGB_CW_CONFIG,
  SOCKET_SWITCH: SOCKET_SWITCH_CONFIG,
  SOCKET_RELAY: SOCKET_RELAY_CONFIG,
  THERMOSTAT: THERMOSTAT_CONFIG,
  DRY_CONTACT: DRY_CONTACT_CONFIG,
  VCAL_SOCKET: VCAL_SOCKET_CONFIG,
  T3_SWITCH: T3_SWITCH_CONFIG,
  T3_DIMMER: T3_DIMMER_CONFIG,
  POWER_POINT: POWER_POINT_CONFIG
}; 